/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArgDeclList extends PArgDeclList
{
    private TIdentifier _identifier_;
    private PTypeDecl _typeDecl_;
    private final LinkedList<PArgList> _argList_ = new LinkedList<PArgList>();

    public AArgDeclList()
    {
        // Constructor
    }

    public AArgDeclList(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PTypeDecl _typeDecl_,
        @SuppressWarnings("hiding") List<?> _argList_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setTypeDecl(_typeDecl_);

        setArgList(_argList_);

    }

    @Override
    public Object clone()
    {
        return new AArgDeclList(
            cloneNode(this._identifier_),
            cloneNode(this._typeDecl_),
            cloneList(this._argList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgDeclList(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PTypeDecl getTypeDecl()
    {
        return this._typeDecl_;
    }

    public void setTypeDecl(PTypeDecl node)
    {
        if(this._typeDecl_ != null)
        {
            this._typeDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDecl_ = node;
    }

    public LinkedList<PArgList> getArgList()
    {
        return this._argList_;
    }

    public void setArgList(List<?> list)
    {
        for(PArgList e : this._argList_)
        {
            e.parent(null);
        }
        this._argList_.clear();

        for(Object obj_e : list)
        {
            PArgList e = (PArgList) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argList_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._typeDecl_)
            + toString(this._argList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._typeDecl_ == child)
        {
            this._typeDecl_ = null;
            return;
        }

        if(this._argList_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._typeDecl_ == oldChild)
        {
            setTypeDecl((PTypeDecl) newChild);
            return;
        }

        for(ListIterator<PArgList> i = this._argList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgList) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
