/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArgList extends PArgList
{
    private TSemicolon _semicolon_;
    private TIdentifier _identifier_;
    private PTypeDecl _typeDecl_;

    public AArgList()
    {
        // Constructor
    }

    public AArgList(
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PTypeDecl _typeDecl_)
    {
        // Constructor
        setSemicolon(_semicolon_);

        setIdentifier(_identifier_);

        setTypeDecl(_typeDecl_);

    }

    @Override
    public Object clone()
    {
        return new AArgList(
            cloneNode(this._semicolon_),
            cloneNode(this._identifier_),
            cloneNode(this._typeDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgList(this);
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PTypeDecl getTypeDecl()
    {
        return this._typeDecl_;
    }

    public void setTypeDecl(PTypeDecl node)
    {
        if(this._typeDecl_ != null)
        {
            this._typeDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._semicolon_)
            + toString(this._identifier_)
            + toString(this._typeDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._typeDecl_ == child)
        {
            this._typeDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._typeDecl_ == oldChild)
        {
            setTypeDecl((PTypeDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
