/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArrayExpressionLast extends PExpressionLast
{
    private TIdentifier _identifier_;
    private final LinkedList<PBraceExpr> _braceExpr_ = new LinkedList<PBraceExpr>();

    public AArrayExpressionLast()
    {
        // Constructor
    }

    public AArrayExpressionLast(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _braceExpr_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setBraceExpr(_braceExpr_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExpressionLast(
            cloneNode(this._identifier_),
            cloneList(this._braceExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExpressionLast(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PBraceExpr> getBraceExpr()
    {
        return this._braceExpr_;
    }

    public void setBraceExpr(List<?> list)
    {
        for(PBraceExpr e : this._braceExpr_)
        {
            e.parent(null);
        }
        this._braceExpr_.clear();

        for(Object obj_e : list)
        {
            PBraceExpr e = (PBraceExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._braceExpr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._braceExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._braceExpr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PBraceExpr> i = this._braceExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PBraceExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
