/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AClassHead extends PClassHead
{
    private TClass _cls_;
    private TIdentifier _className_;
    private PClassInherits _classInherits_;
    private TIs _is_;
    private final LinkedList<TNewLine> _newLine_ = new LinkedList<TNewLine>();

    public AClassHead()
    {
        // Constructor
    }

    public AClassHead(
        @SuppressWarnings("hiding") TClass _cls_,
        @SuppressWarnings("hiding") TIdentifier _className_,
        @SuppressWarnings("hiding") PClassInherits _classInherits_,
        @SuppressWarnings("hiding") TIs _is_,
        @SuppressWarnings("hiding") List<?> _newLine_)
    {
        // Constructor
        setCls(_cls_);

        setClassName(_className_);

        setClassInherits(_classInherits_);

        setIs(_is_);

        setNewLine(_newLine_);

    }

    @Override
    public Object clone()
    {
        return new AClassHead(
            cloneNode(this._cls_),
            cloneNode(this._className_),
            cloneNode(this._classInherits_),
            cloneNode(this._is_),
            cloneList(this._newLine_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassHead(this);
    }

    public TClass getCls()
    {
        return this._cls_;
    }

    public void setCls(TClass node)
    {
        if(this._cls_ != null)
        {
            this._cls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cls_ = node;
    }

    public TIdentifier getClassName()
    {
        return this._className_;
    }

    public void setClassName(TIdentifier node)
    {
        if(this._className_ != null)
        {
            this._className_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._className_ = node;
    }

    public PClassInherits getClassInherits()
    {
        return this._classInherits_;
    }

    public void setClassInherits(PClassInherits node)
    {
        if(this._classInherits_ != null)
        {
            this._classInherits_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classInherits_ = node;
    }

    public TIs getIs()
    {
        return this._is_;
    }

    public void setIs(TIs node)
    {
        if(this._is_ != null)
        {
            this._is_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._is_ = node;
    }

    public LinkedList<TNewLine> getNewLine()
    {
        return this._newLine_;
    }

    public void setNewLine(List<?> list)
    {
        for(TNewLine e : this._newLine_)
        {
            e.parent(null);
        }
        this._newLine_.clear();

        for(Object obj_e : list)
        {
            TNewLine e = (TNewLine) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._newLine_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cls_)
            + toString(this._className_)
            + toString(this._classInherits_)
            + toString(this._is_)
            + toString(this._newLine_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cls_ == child)
        {
            this._cls_ = null;
            return;
        }

        if(this._className_ == child)
        {
            this._className_ = null;
            return;
        }

        if(this._classInherits_ == child)
        {
            this._classInherits_ = null;
            return;
        }

        if(this._is_ == child)
        {
            this._is_ = null;
            return;
        }

        if(this._newLine_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cls_ == oldChild)
        {
            setCls((TClass) newChild);
            return;
        }

        if(this._className_ == oldChild)
        {
            setClassName((TIdentifier) newChild);
            return;
        }

        if(this._classInherits_ == oldChild)
        {
            setClassInherits((PClassInherits) newChild);
            return;
        }

        if(this._is_ == oldChild)
        {
            setIs((TIs) newChild);
            return;
        }

        for(ListIterator<TNewLine> i = this._newLine_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TNewLine) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
