/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AMethodCallExpression extends PExpression
{
    private PExpression _caller_;
    private TIdentifier _method_;
    private final LinkedList<PExpression> _args_ = new LinkedList<PExpression>();

    public AMethodCallExpression()
    {
        // Constructor
    }

    public AMethodCallExpression(
        @SuppressWarnings("hiding") PExpression _caller_,
        @SuppressWarnings("hiding") TIdentifier _method_,
        @SuppressWarnings("hiding") List<?> _args_)
    {
        // Constructor
        setCaller(_caller_);

        setMethod(_method_);

        setArgs(_args_);

    }

    @Override
    public Object clone()
    {
        return new AMethodCallExpression(
            cloneNode(this._caller_),
            cloneNode(this._method_),
            cloneList(this._args_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodCallExpression(this);
    }

    public PExpression getCaller()
    {
        return this._caller_;
    }

    public void setCaller(PExpression node)
    {
        if(this._caller_ != null)
        {
            this._caller_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caller_ = node;
    }

    public TIdentifier getMethod()
    {
        return this._method_;
    }

    public void setMethod(TIdentifier node)
    {
        if(this._method_ != null)
        {
            this._method_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._method_ = node;
    }

    public LinkedList<PExpression> getArgs()
    {
        return this._args_;
    }

    public void setArgs(List<?> list)
    {
        for(PExpression e : this._args_)
        {
            e.parent(null);
        }
        this._args_.clear();

        for(Object obj_e : list)
        {
            PExpression e = (PExpression) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._args_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caller_)
            + toString(this._method_)
            + toString(this._args_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caller_ == child)
        {
            this._caller_ = null;
            return;
        }

        if(this._method_ == child)
        {
            this._method_ = null;
            return;
        }

        if(this._args_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caller_ == oldChild)
        {
            setCaller((PExpression) newChild);
            return;
        }

        if(this._method_ == oldChild)
        {
            setMethod((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PExpression> i = this._args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpression) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
