/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AMethodDecl extends PMethodDecl
{
    private PMethodHead _methodHead_;
    private PMethodBody _methodBody_;
    private PMethodEnd _methodEnd_;

    public AMethodDecl()
    {
        // Constructor
    }

    public AMethodDecl(
        @SuppressWarnings("hiding") PMethodHead _methodHead_,
        @SuppressWarnings("hiding") PMethodBody _methodBody_,
        @SuppressWarnings("hiding") PMethodEnd _methodEnd_)
    {
        // Constructor
        setMethodHead(_methodHead_);

        setMethodBody(_methodBody_);

        setMethodEnd(_methodEnd_);

    }

    @Override
    public Object clone()
    {
        return new AMethodDecl(
            cloneNode(this._methodHead_),
            cloneNode(this._methodBody_),
            cloneNode(this._methodEnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodDecl(this);
    }

    public PMethodHead getMethodHead()
    {
        return this._methodHead_;
    }

    public void setMethodHead(PMethodHead node)
    {
        if(this._methodHead_ != null)
        {
            this._methodHead_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodHead_ = node;
    }

    public PMethodBody getMethodBody()
    {
        return this._methodBody_;
    }

    public void setMethodBody(PMethodBody node)
    {
        if(this._methodBody_ != null)
        {
            this._methodBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodBody_ = node;
    }

    public PMethodEnd getMethodEnd()
    {
        return this._methodEnd_;
    }

    public void setMethodEnd(PMethodEnd node)
    {
        if(this._methodEnd_ != null)
        {
            this._methodEnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodEnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._methodHead_)
            + toString(this._methodBody_)
            + toString(this._methodEnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._methodHead_ == child)
        {
            this._methodHead_ = null;
            return;
        }

        if(this._methodBody_ == child)
        {
            this._methodBody_ = null;
            return;
        }

        if(this._methodEnd_ == child)
        {
            this._methodEnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._methodHead_ == oldChild)
        {
            setMethodHead((PMethodHead) newChild);
            return;
        }

        if(this._methodBody_ == oldChild)
        {
            setMethodBody((PMethodBody) newChild);
            return;
        }

        if(this._methodEnd_ == oldChild)
        {
            setMethodEnd((PMethodEnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
