/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AMethodCallExpr extends PMethodCallExpr
{
    private PExpressionLast _expressionLast_;
    private TDot _dot_;

    public AMethodCallExpr()
    {
        // Constructor
    }

    public AMethodCallExpr(
        @SuppressWarnings("hiding") PExpressionLast _expressionLast_,
        @SuppressWarnings("hiding") TDot _dot_)
    {
        // Constructor
        setExpressionLast(_expressionLast_);

        setDot(_dot_);

    }

    @Override
    public Object clone()
    {
        return new AMethodCallExpr(
            cloneNode(this._expressionLast_),
            cloneNode(this._dot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodCallExpr(this);
    }

    public PExpressionLast getExpressionLast()
    {
        return this._expressionLast_;
    }

    public void setExpressionLast(PExpressionLast node)
    {
        if(this._expressionLast_ != null)
        {
            this._expressionLast_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLast_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLast_)
            + toString(this._dot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLast_ == child)
        {
            this._expressionLast_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLast_ == oldChild)
        {
            setExpressionLast((PExpressionLast) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
