/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplyExpressionLvl1 extends PExpressionLvl1
{
    private PExpressionLvl1 _expressionLvl1_;
    private TMultiply _multiply_;
    private PExpressionLvl0 _expressionLvl0_;

    public AMultiplyExpressionLvl1()
    {
        // Constructor
    }

    public AMultiplyExpressionLvl1(
        @SuppressWarnings("hiding") PExpressionLvl1 _expressionLvl1_,
        @SuppressWarnings("hiding") TMultiply _multiply_,
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_)
    {
        // Constructor
        setExpressionLvl1(_expressionLvl1_);

        setMultiply(_multiply_);

        setExpressionLvl0(_expressionLvl0_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplyExpressionLvl1(
            cloneNode(this._expressionLvl1_),
            cloneNode(this._multiply_),
            cloneNode(this._expressionLvl0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplyExpressionLvl1(this);
    }

    public PExpressionLvl1 getExpressionLvl1()
    {
        return this._expressionLvl1_;
    }

    public void setExpressionLvl1(PExpressionLvl1 node)
    {
        if(this._expressionLvl1_ != null)
        {
            this._expressionLvl1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl1_ = node;
    }

    public TMultiply getMultiply()
    {
        return this._multiply_;
    }

    public void setMultiply(TMultiply node)
    {
        if(this._multiply_ != null)
        {
            this._multiply_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiply_ = node;
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl1_)
            + toString(this._multiply_)
            + toString(this._expressionLvl0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl1_ == child)
        {
            this._expressionLvl1_ = null;
            return;
        }

        if(this._multiply_ == child)
        {
            this._multiply_ = null;
            return;
        }

        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl1_ == oldChild)
        {
            setExpressionLvl1((PExpressionLvl1) newChild);
            return;
        }

        if(this._multiply_ == oldChild)
        {
            setMultiply((TMultiply) newChild);
            return;
        }

        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
