/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ANegExpressionLvl0 extends PExpressionLvl0
{
    private TMinus _minus_;
    private PExpressionLvl0 _expressionLvl0_;

    public ANegExpressionLvl0()
    {
        // Constructor
    }

    public ANegExpressionLvl0(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_)
    {
        // Constructor
        setMinus(_minus_);

        setExpressionLvl0(_expressionLvl0_);

    }

    @Override
    public Object clone()
    {
        return new ANegExpressionLvl0(
            cloneNode(this._minus_),
            cloneNode(this._expressionLvl0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegExpressionLvl0(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._expressionLvl0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
