/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpressionLvl0 extends PExpressionLvl0
{
    private TLogicalNot _logicalNot_;
    private PExpressionLvl0 _expressionLvl0_;

    public ANotExpressionLvl0()
    {
        // Constructor
    }

    public ANotExpressionLvl0(
        @SuppressWarnings("hiding") TLogicalNot _logicalNot_,
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_)
    {
        // Constructor
        setLogicalNot(_logicalNot_);

        setExpressionLvl0(_expressionLvl0_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpressionLvl0(
            cloneNode(this._logicalNot_),
            cloneNode(this._expressionLvl0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpressionLvl0(this);
    }

    public TLogicalNot getLogicalNot()
    {
        return this._logicalNot_;
    }

    public void setLogicalNot(TLogicalNot node)
    {
        if(this._logicalNot_ != null)
        {
            this._logicalNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalNot_ = node;
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicalNot_)
            + toString(this._expressionLvl0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicalNot_ == child)
        {
            this._logicalNot_ = null;
            return;
        }

        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicalNot_ == oldChild)
        {
            setLogicalNot((TLogicalNot) newChild);
            return;
        }

        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
