/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AParenthExpressionLast extends PExpressionLast
{
    private TOparen _oparen_;
    private PExpression _expression_;
    private TCparen _cparen_;

    public AParenthExpressionLast()
    {
        // Constructor
    }

    public AParenthExpressionLast(
        @SuppressWarnings("hiding") TOparen _oparen_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TCparen _cparen_)
    {
        // Constructor
        setOparen(_oparen_);

        setExpression(_expression_);

        setCparen(_cparen_);

    }

    @Override
    public Object clone()
    {
        return new AParenthExpressionLast(
            cloneNode(this._oparen_),
            cloneNode(this._expression_),
            cloneNode(this._cparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenthExpressionLast(this);
    }

    public TOparen getOparen()
    {
        return this._oparen_;
    }

    public void setOparen(TOparen node)
    {
        if(this._oparen_ != null)
        {
            this._oparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oparen_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TCparen getCparen()
    {
        return this._cparen_;
    }

    public void setCparen(TCparen node)
    {
        if(this._cparen_ != null)
        {
            this._cparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oparen_)
            + toString(this._expression_)
            + toString(this._cparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oparen_ == child)
        {
            this._oparen_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._cparen_ == child)
        {
            this._cparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oparen_ == oldChild)
        {
            setOparen((TOparen) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._cparen_ == oldChild)
        {
            setCparen((TCparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
