/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class APosExpressionLvl0 extends PExpressionLvl0
{
    private TPlus _plus_;
    private PExpressionLvl0 _expressionLvl0_;

    public APosExpressionLvl0()
    {
        // Constructor
    }

    public APosExpressionLvl0(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_)
    {
        // Constructor
        setPlus(_plus_);

        setExpressionLvl0(_expressionLvl0_);

    }

    @Override
    public Object clone()
    {
        return new APosExpressionLvl0(
            cloneNode(this._plus_),
            cloneNode(this._expressionLvl0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPosExpressionLvl0(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._expressionLvl0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
