/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ASpaceStart extends PStart
{
    private TNewLine _newLine_;
    private PStart _start_;

    public ASpaceStart()
    {
        // Constructor
    }

    public ASpaceStart(
        @SuppressWarnings("hiding") TNewLine _newLine_,
        @SuppressWarnings("hiding") PStart _start_)
    {
        // Constructor
        setNewLine(_newLine_);

        setStart(_start_);

    }

    @Override
    public Object clone()
    {
        return new ASpaceStart(
            cloneNode(this._newLine_),
            cloneNode(this._start_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpaceStart(this);
    }

    public TNewLine getNewLine()
    {
        return this._newLine_;
    }

    public void setNewLine(TNewLine node)
    {
        if(this._newLine_ != null)
        {
            this._newLine_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newLine_ = node;
    }

    public PStart getStart()
    {
        return this._start_;
    }

    public void setStart(PStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._newLine_)
            + toString(this._start_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._newLine_ == child)
        {
            this._newLine_ = null;
            return;
        }

        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._newLine_ == oldChild)
        {
            setNewLine((TNewLine) newChild);
            return;
        }

        if(this._start_ == oldChild)
        {
            setStart((PStart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
