/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.lexer;

import java.io.*;
import com.bju.cps450.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNewLine(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLineContinue(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpace(line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTab(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClass(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNull(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNew(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMe(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLoop(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIs(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInherits(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBegin(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogicalAnd(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogicalOr(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogicalNot(line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringLit(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringConcat(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivide(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultiply(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGteq(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOparen(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCparen(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObrace(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCbrace(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssignment(line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnterminatedString(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIllegalString(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIllegal(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 1}, {34, 34, 6}, {35, 37, 1}, {38, 38, 7}, {39, 39, 1}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 1}, {61, 61, 19}, {62, 62, 20}, {63, 64, 1}, {65, 90, 21}, {91, 91, 22}, {92, 92, 1}, {93, 93, 23}, {94, 94, 1}, {95, 95, 24}, {96, 96, 1}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 21}, {101, 101, 28}, {102, 102, 29}, {103, 104, 21}, {105, 105, 30}, {106, 107, 21}, {108, 108, 31}, {109, 109, 32}, {110, 110, 33}, {111, 111, 34}, {112, 114, 21}, {115, 115, 35}, {116, 116, 36}, {117, 118, 21}, {119, 119, 37}, {120, 122, 21}, {123, 125, 1}, {126, 126, 38}, {127, 128, 1}, },
            {},
            {},
            {},
            {{10, 10, 39}, },
            {},
            {{0, 9, 40}, {11, 12, 40}, {14, 33, 40}, {34, 34, 41}, {35, 91, 40}, {92, 92, 42}, {93, 128, 40}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 43}, {48, 57, 44}, },
            {},
            {},
            {{48, 57, 45}, },
            {{61, 61, 46}, },
            {},
            {},
            {{61, 61, 47}, },
            {{48, 57, 48}, {65, 90, 49}, {95, 95, 50}, {97, 122, 49}, },
            {},
            {},
            {{10, 10, 51}, {13, 13, 52}, {48, 122, -23}, },
            {{48, 95, -23}, {97, 109, 49}, {110, 110, 53}, {111, 122, 49}, },
            {{48, 95, -23}, {97, 100, 49}, {101, 101, 54}, {102, 110, 49}, {111, 111, 55}, {112, 122, 49}, },
            {{48, 95, -23}, {97, 107, 49}, {108, 108, 56}, {109, 122, 49}, },
            {{48, 107, -29}, {108, 108, 57}, {109, 109, 49}, {110, 110, 58}, {111, 122, 49}, },
            {{48, 95, -23}, {97, 97, 59}, {98, 113, 49}, {114, 114, 60}, {115, 122, 49}, },
            {{48, 95, -23}, {97, 101, 49}, {102, 102, 61}, {103, 109, 49}, {110, 110, 62}, {111, 114, 49}, {115, 115, 63}, {116, 122, 49}, },
            {{48, 95, -23}, {97, 110, 49}, {111, 111, 64}, {112, 122, 49}, },
            {{48, 100, -28}, {101, 101, 65}, {102, 122, 49}, },
            {{48, 100, -28}, {101, 101, 66}, {102, 110, 49}, {111, 111, 67}, {112, 116, 49}, {117, 117, 68}, {118, 122, 49}, },
            {{48, 95, -23}, {97, 113, 49}, {114, 114, 69}, {115, 122, 49}, },
            {{48, 95, -23}, {97, 115, 49}, {116, 116, 70}, {117, 122, 49}, },
            {{48, 95, -23}, {97, 103, 49}, {104, 104, 71}, {105, 113, 49}, {114, 114, 72}, {115, 122, 49}, },
            {{48, 103, -38}, {104, 104, 73}, {105, 122, 49}, },
            {{0, 9, 74}, {11, 12, 74}, {14, 128, 74}, },
            {},
            {{0, 33, -8}, {34, 34, 75}, {35, 128, -8}, },
            {},
            {{0, 9, 76}, {11, 12, 76}, {14, 33, 76}, {34, 34, 77}, {35, 47, 76}, {48, 48, 78}, {49, 49, 79}, {50, 55, 80}, {56, 91, 76}, {92, 92, 81}, {93, 101, 76}, {102, 102, 82}, {103, 109, 76}, {110, 110, 83}, {111, 113, 76}, {114, 114, 84}, {115, 115, 76}, {116, 116, 85}, {117, 128, 76}, },
            {{45, 57, -15}, },
            {{48, 57, 45}, },
            {{48, 57, 45}, },
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {},
            {},
            {{48, 95, -23}, {97, 99, 49}, {100, 100, 86}, {101, 122, 49}, },
            {{48, 95, -23}, {97, 102, 49}, {103, 103, 87}, {104, 122, 49}, },
            {{48, 110, -33}, {111, 111, 88}, {112, 122, 49}, },
            {{48, 95, -23}, {97, 97, 89}, {98, 122, 49}, },
            {{48, 95, -23}, {97, 114, 49}, {115, 115, 90}, {116, 122, 49}, },
            {{48, 99, -55}, {100, 100, 91}, {101, 122, 49}, },
            {{48, 107, -29}, {108, 108, 92}, {109, 122, 49}, },
            {{48, 110, -33}, {111, 111, 93}, {112, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 103, -38}, {104, 104, 94}, {105, 115, 49}, {116, 116, 95}, {117, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 110, -33}, {111, 111, 96}, {112, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 118, 49}, {119, 119, 97}, {120, 122, 49}, },
            {{48, 115, -37}, {116, 116, 98}, {117, 122, 49}, },
            {{48, 107, -29}, {108, 108, 99}, {109, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 113, -36}, {114, 114, 100}, {115, 122, 49}, },
            {{48, 100, -28}, {101, 101, 101}, {102, 122, 49}, },
            {{48, 95, -23}, {97, 116, 49}, {117, 117, 102}, {118, 122, 49}, },
            {{48, 95, -23}, {97, 104, 49}, {105, 105, 103}, {106, 122, 49}, },
            {{0, 128, -40}, },
            {},
            {{0, 33, -44}, {34, 34, 104}, {35, 91, 76}, {92, 92, 105}, {93, 128, 76}, },
            {{0, 128, -42}, },
            {{0, 34, -78}, {35, 47, 76}, {48, 48, 106}, {49, 49, 107}, {50, 55, 106}, {56, 91, 76}, {92, 128, -78}, },
            {{0, 47, -80}, {48, 50, 106}, {51, 51, 108}, {52, 55, 106}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 55, 106}, {56, 128, -80}, },
            {{0, 9, 109}, {11, 12, 109}, {14, 33, 109}, {34, 34, 110}, {35, 47, 109}, {48, 48, 111}, {49, 49, 112}, {50, 55, 113}, {56, 91, 109}, {92, 92, 114}, {93, 101, 109}, {102, 102, 115}, {103, 109, 109}, {110, 110, 116}, {111, 113, 109}, {114, 114, 117}, {115, 115, 109}, {116, 116, 118}, {117, 128, 109}, },
            {{0, 33, -83}, {34, 34, 41}, {35, 91, 109}, {92, 92, 119}, {93, 128, 109}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{48, 122, -23}, },
            {{48, 104, -75}, {105, 105, 120}, {106, 122, 49}, },
            {{48, 107, -29}, {108, 108, 121}, {109, 122, 49}, },
            {{48, 114, -59}, {115, 115, 122}, {116, 122, 49}, },
            {{48, 100, -28}, {101, 101, 123}, {102, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 114, -59}, {115, 115, 124}, {116, 122, 49}, },
            {{48, 95, -23}, {97, 108, 49}, {109, 109, 125}, {110, 122, 49}, },
            {{48, 100, -28}, {101, 101, 126}, {102, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 111, 49}, {112, 112, 127}, {113, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 107, -29}, {108, 108, 128}, {109, 122, 49}, },
            {{48, 104, -75}, {105, 105, 129}, {106, 122, 49}, },
            {{48, 109, -27}, {110, 110, 130}, {111, 122, 49}, },
            {{48, 100, -28}, {101, 101, 131}, {102, 122, 49}, },
            {{48, 107, -29}, {108, 108, 132}, {109, 122, 49}, },
            {},
            {{0, 33, -44}, {34, 34, 133}, {35, 47, 76}, {48, 48, 134}, {49, 49, 135}, {50, 55, 136}, {56, 91, 76}, {92, 92, 137}, {93, 101, 76}, {102, 102, 138}, {103, 109, 76}, {110, 110, 139}, {111, 113, 76}, {114, 114, 140}, {115, 115, 76}, {116, 116, 141}, {117, 128, 76}, },
            {{0, 47, -80}, {48, 55, 142}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 48, 142}, {49, 49, 143}, {50, 50, 144}, {51, 51, 142}, {52, 52, 145}, {53, 53, 146}, {54, 55, 142}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 51, 142}, {52, 52, 147}, {53, 55, 142}, {56, 128, -80}, },
            {{0, 128, -84}, },
            {{0, 128, -78}, },
            {{0, 34, -84}, {35, 47, 109}, {48, 48, 148}, {49, 49, 149}, {50, 55, 148}, {56, 91, 109}, {92, 128, -84}, },
            {{0, 47, -113}, {48, 50, 148}, {51, 51, 150}, {52, 55, 148}, {56, 128, -113}, },
            {{0, 47, -113}, {48, 55, 148}, {56, 128, -113}, },
            {{0, 33, -44}, {34, 34, 151}, {35, 47, 76}, {48, 48, 152}, {49, 49, 153}, {50, 55, 154}, {56, 91, 76}, {92, 92, 155}, {93, 101, 76}, {102, 102, 156}, {103, 109, 76}, {110, 110, 157}, {111, 113, 76}, {114, 114, 158}, {115, 115, 76}, {116, 116, 159}, {117, 128, 76}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -116}, },
            {{48, 109, -27}, {110, 110, 160}, {111, 122, 49}, },
            {{48, 100, -28}, {101, 101, 161}, {102, 122, 49}, },
            {{48, 114, -59}, {115, 115, 162}, {116, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 100, -28}, {101, 101, 163}, {102, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 113, -36}, {114, 114, 164}, {115, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 109, -27}, {110, 110, 165}, {111, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -28}, {101, 101, 166}, {102, 122, 49}, },
            {{0, 128, -78}, },
            {{0, 47, -80}, {48, 48, 167}, {49, 49, 168}, {50, 55, 167}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 50, 167}, {51, 51, 169}, {52, 55, 167}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 55, 167}, {56, 128, -80}, },
            {{0, 128, -107}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 47, -113}, {48, 55, 170}, {56, 128, -113}, },
            {{0, 47, -113}, {48, 48, 170}, {49, 49, 171}, {50, 50, 172}, {51, 51, 170}, {52, 52, 173}, {53, 53, 174}, {54, 55, 170}, {56, 128, -113}, },
            {{0, 47, -113}, {48, 51, 170}, {52, 52, 175}, {53, 55, 170}, {56, 128, -113}, },
            {{0, 128, -84}, },
            {{0, 47, -80}, {48, 48, 176}, {49, 49, 177}, {50, 55, 176}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 50, 176}, {51, 51, 178}, {52, 55, 176}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 55, 176}, {56, 128, -80}, },
            {{0, 128, -83}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 179}, {98, 122, 49}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 104, -75}, {105, 105, 180}, {106, 122, 49}, },
            {{48, 102, -56}, {103, 103, 181}, {104, 122, 49}, },
            {{48, 122, -23}, },
            {{0, 47, -80}, {48, 55, 182}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 48, 182}, {49, 49, 183}, {50, 50, 184}, {51, 51, 182}, {52, 52, 185}, {53, 53, 186}, {54, 55, 182}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 51, 182}, {52, 52, 187}, {53, 55, 182}, {56, 128, -80}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 47, -80}, {48, 55, 188}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 48, 188}, {49, 49, 189}, {50, 50, 190}, {51, 51, 188}, {52, 52, 191}, {53, 53, 192}, {54, 55, 188}, {56, 128, -80}, },
            {{0, 47, -80}, {48, 51, 188}, {52, 52, 193}, {53, 55, 188}, {56, 128, -80}, },
            {{48, 109, -27}, {110, 110, 194}, {111, 122, 49}, },
            {{48, 115, -37}, {116, 116, 195}, {117, 122, 49}, },
            {{48, 122, -23}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -78}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{0, 128, -84}, },
            {{48, 122, -23}, },
            {{48, 114, -59}, {115, 115, 196}, {116, 122, 49}, },
            {{48, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 49, 4, 0, 49, 2, 47, 29, 39, 40, 33, 30, 44, 31, 38, 32, 28, 37, 43, 36, 34, 46, 41, 42, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 3, 0, 47, 27, 47, -1, 28, 28, 45, 35, 46, 46, 46, 1, 1, 46, 46, 46, 46, 46, 46, 46, 46, 19, 46, 16, 46, 14, 46, 46, 46, 25, 46, 46, 46, 46, 3, 27, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 24, 46, 46, 46, 46, 21, 46, 46, 46, 17, 46, 13, 26, 46, 46, 46, 46, 46, 48, 47, 47, 47, 47, 47, 27, 47, 47, 47, 47, 47, 47, 47, 47, 47, 46, 46, 46, 20, 46, 9, 46, 15, 12, 46, 6, 7, 46, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 23, 46, 10, 8, 46, 46, 11, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 46, 46, 5, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 22, 46, 18, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
